### ISSUE TITLE
Make GWT an executable binary

### ISSUE THREAD

**Issue by ghost** [wright-io/givenwhenthen#12]
Since not all Node projects use cake, I think it would be easier to integrate this module into existing apps by making it an executable binary (a la mocha) installed to the `./node_modules/.bin` directory. This would allow us to pass in some different config options to allow `givenwhenthen` to be extended by other libraries too.

Here's how I think it could work:

`cd myProject`
`./node_modules/.bin/givenwhenthen --config path/to/my/config --tests path/to/my/tests/*.js`

The consuming module could then map `npm test` to `./node_modules/.bin/givenwhenthen --config path/to/my/config --tests path/to/my/tests/*.js` (this would let tests be run through Travis-ci too!)

@philcockfield @wright-io what do you think?

**Comment by wright-io** [comment]
A little way overdue cleanup.

**Comment by wright-io** [comment]
A little way overdue cleanup.
